;; Most of these are from Yegge's 10 Effective Emacs Tips
(global-set-key "\C-X\C-B" 'ibuffer)
;(global-set-key "\C-\\" 'dabbrev-expand)
(global-set-key "\M-/" 'hippie-expand)
(global-set-key "\C-i" 'indent-relative)
(global-set-key "\C-c@" 'uncomment-region)
(global-set-key "\M-s" 'isearch-forward-regexp)
(global-set-key "\M-r" 'isearch-backward-regexp)
(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key "\C-c\C-m" 'execute-extended-command)
(global-set-key "\C-w" 'backward-kill-word)
(global-set-key "\C-x\C-k" 'kill-region)
(global-set-key "\C-c\C-k" 'kill-region)
(global-set-key (kbd "H-0") 'call-last-kbd-macro)
(global-set-key [delete] 'delete-char)
(global-set-key [kp-delete] 'delete-char)
(global-set-key "\M-\r" 'next-multiframe-window)
(global-unset-key "\C-xm") ; turn off compose-mail

(global-set-key [(shift down)] 'next-line)
(global-set-key [(shift up)] 'previous-line)
(global-set-key [down] 'scroll-up-keep-cursor)
(global-set-key [up] 'scroll-down-keep-cursor)

; enable skeleton-pair for these to work (replaced by smartparen)
;; (global-set-key "["  'skeleton-pair-insert-maybe)
;; (global-set-key "("  'skeleton-pair-insert-maybe)
;; (global-set-key "{"  'skeleton-pair-insert-maybe)
;; (global-set-key "\"" 'skeleton-pair-insert-maybe)
;; ;(global-set-key "'"  'skeleton-pair-insert-maybe)

(defalias 'qrr 'query-replace-regexp)
(defalias 'lml 'list-matching-lines)
(defalias 'fr 'fill-region)
(defalias 'kr 'kill-region)
(defalias 'fo 'ff-find-other-file)
(defalias 'tt 'toggle-truncate-lines)
(defalias 'sw 'select-current-word)
(defalias 'is 'ispell-word)
(defalias 'sd 'search-docset)
(defalias 'fgs 'find-grep-source)
(defalias 'fg 'find-grep-source-at-point)
(defalias 'bb 'bury-buffer)
(defalias 'ttl 'toggle-truncate-lines)
(defalias 'bj 'browse-jira)

(provide 'my-keybindings)
